services:
  postgres:
    image: ghcr.io/fboulnois/pg_uuidv7:1.6.0
    container_name: todo_container
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: todo_list
    ports:
      - "5431:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
    networks:
      - todo_network

networks:
  todo_network:

volumes:
  pg_data: